import { StoreProvider } from "@/store/StoreProvider"
import "./globals.css"
import { Roboto } from "next/font/google"
import { AntdRegistry } from '@ant-design/nextjs-registry';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const roboto = Roboto({subsets: ['latin'], weight: ["400", "700", "500", "900", "300"]})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    // <StoreProvider>
    //   <html lang="en">
    //     <body className={roboto.className}>
    //       {children}
    //     </body>
    //   </html>
    // </StoreProvider>
    <html lang="en">
      <body className={roboto.className}>
        <StoreProvider>
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </StoreProvider>
      </body>
    </html>
    
  )
}
